# application.yml

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
    com.example: debug
